### ISSUE TITLE
EVALB/evalb报错

### ISSUE THREAD

**Issue by niceeeeharamiko** [HoraceXIaoyiBao/OTP4ABSA-ACL2023#1]
/bin/sh: 1: /home/disk2/zfl/lab/OTP4ABSA-ACL2023-main/OPT/EVALB/evalb: Permission denied运行test时出现了这个问题，无法读取结果

**Comment by HoraceXIaoyiBao** [comment]
Permission denied的话大概率是你自己服务器权限问题，sudo或者看看读写权限
